### ISSUE TITLE
I would like to have batch / exec for ssdb, how do I join multiple commands?

### ISSUE THREAD

**Issue by unisqu** [ssdb/gossdb#18]
Can I join two commands by joining command lines with "\n"? or \r\n?
Any better suggestions?

**Comment by ideawu** [comment]
There is better way to do this:

```
ssdb.Send("set", "a", "123");
ssdb.Send("get", "a");
r1 = ssdb.Recv();
r2 = ssdb.Recv();
```

You should call Recv() the times you called Send().
